// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5Opr-0Uvg7Q8eeOr9ndUQmdYNbcbDAA',
    appId: '1:88593694399:web:81fbef717584d1bd8b500a',
    messagingSenderId: '88593694399',
    projectId: 'flutter-chat-hj',
    authDomain: 'flutter-chat-hj.firebaseapp.com',
    storageBucket: 'flutter-chat-hj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKt_I3TV6jS8PbiM0pkjwSl8EGXABEBbk',
    appId: '1:88593694399:android:58b27b11c915a8338b500a',
    messagingSenderId: '88593694399',
    projectId: 'flutter-chat-hj',
    storageBucket: 'flutter-chat-hj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4o-0pCT8aH8Cak04hCzXjEAuhrBRYbc',
    appId: '1:88593694399:ios:adf01ba108e1a50d8b500a',
    messagingSenderId: '88593694399',
    projectId: 'flutter-chat-hj',
    storageBucket: 'flutter-chat-hj.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb4o-0pCT8aH8Cak04hCzXjEAuhrBRYbc',
    appId: '1:88593694399:ios:c35ece4dd7e1772e8b500a',
    messagingSenderId: '88593694399',
    projectId: 'flutter-chat-hj',
    storageBucket: 'flutter-chat-hj.appspot.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
